baseurl = "www.andimarek.com"
languageCode = "en-us"
title = "andimarek.com"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Andreas Marek"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    twitter = "andimarek"
    github = "andimarek"
    # linkedin = "andimarek"
    # Disqus shortname
    # disqus = "Your disqus shortname"
    # Google Analytics API key.
    ga_api_key = "Your Google Analytics tracking id"
    # Mixpanel API key.
    # mixpanel_api_key = "Your Mixpanel API key"
    # author = "Your Name"
    # avatar = "/andi.jpeg"
    # contact = "Your contact link (ex. mailto:foo@example.com)"
    # bio = "Your short bio"
    # Short subtitle/tagline. This is displayed in the header.
    # subtitle = "Short subtitle/tagline of your blog"
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.
